---

- hosts: R1
  gather_facts: False

  vars:
    _token: cYrogcQrJAv-zqaaoNjBRljNIMF3j8AQ52F-tOBC
    _light_id: 9
    _data_red: '{"on":True, "sat":254, "bri":254,"hue":5000,"ct": 500, "xy": [0.6792,0.3038]}'
    _data_green: '{"on":True, "sat":254, "bri":254,"hue":5000,"ct": 500, "xy": [0.2688, 0.6171]}'
    _data_off: '{"on":False}'


  tasks:
  - name: Read in parse_genie role
    include_role:
      name: clay584.parse_genie

  - name: Turn Lights Off
    uri:
      url: "http://192.168.1.86/api/{{ _token }}/lights/{{ _light_id }}/state"
      method: PUT
      body: "{{ _data_off }}"
      body_format: json
      headers: 
        Accept: application/json 
      return_content: 'True'
      validate_certs: no
      force_basic_auth: no
      follow_redirects: 'True'

  - name: Run show interfaces command
    ios_command:
      commands: show ip route
    register: interfaces

  - name: Print Structured Data
    debug:
      msg: "{{ interfaces['stdout'][0] | parse_genie(command='show ip route', os='iosxe') }}"
    delegate_to: localhost
    register: _output

  - set_fact:
      _routes: "{{ _output.msg|json_query('vrf.default.address_family.ipv4.routes.keys(@)') }}"

  - set_fact:
      _routecheck: "{{ _routes | length }}"

  - name: Turn Green Light On
    uri:
      url: "http://192.168.1.86/api/{{ _token }}/lights/{{ _light_id }}/state"
      method: PUT
      body: "{{ _data_green }}"
      body_format: json
      headers: 
        Accept: application/json 
      return_content: 'True'
      validate_certs: no
      force_basic_auth: no
      follow_redirects: 'True'
    when: _routecheck == '6'

  - name: Turn Red Light On
    uri:
      url: "http://192.168.1.86/api/{{ _token }}/lights/{{ _light_id }}/state"
      method: PUT
      body: "{{ _data_red }}"
      body_format: json
      headers: 
        Accept: application/json 
      return_content: 'True'
      validate_certs: no
      force_basic_auth: no
      follow_redirects: 'True'
    when: _routecheck != '6'
